name: "Build Corne 5 nice_oled (vertical)"

on: workflow_dispatch

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_oled","corne_right nice_oled"]'
      modules: '["mctechnology17/zmk-nice-oled/main"]'
      kconfig: '["CONFIG_ZMK_KEYBOARD_NAME=\"Corne 5\""]'
